sugarcube-2:
  macros:
    # widgets
    building: {}
    profile: {}
    tooltip: {}
    money: {}
    shop: {}
    factionResource: {}

    # misc
    numberslider: {}
    numberbox:
      container: true
    notify:
      container: true
    fadein:
      container: true
    fadeout:
      container: true
    ifdefprint: {}
    idp: {}
    # live-update.js
    live: {}
    l: {}
    lh: {}
    liveblock:
      container: true
    lb:
      container: true
    update: {}
    upd: {}
