name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Caching:
      # see https://github.com/actions/cache/blob/master/examples.md#node---yarn for details.

      - name: Set path to yarn cache
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      # Install dependencies:
      - run: yarn

      # Run tests:
      - run: yarn test

      # Install twine compiler:
      - run: yarn install-compiler
      
      # Fix permissions:
      - name: Make tweego executable
        run: chmod +x ./.twine/tweego
  
      # Build:
      - run: yarn build

      # Deploy to github pages.
      - if: ${{ github.ref == 'master' && github.event_name == 'push' }}
        run: yarn deploy